# Generated by Django 3.0.7 on 2020-06-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200618_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='text',
            field=models.CharField(max_length=60),
        ),
    ]
